export enum ActionType {
  FETCH_BUSINESSES_START = "FETCH_BUSINESSES_START",
  FETCH_BUSINESSES_SUCCESS = "FETCH_BUSINESSES_SUCCESS",
  FETCH_BUSINESSES_FAILURE = "FETCH_BUSINESSES_FAILURE",
  FETCH_BUSINESSES_REQUEST = "FETCH_BUSINESSES_REQUEST",
  UPDATE_BUSINESS = "UPDATE_BUSINESS",
  LOAD_MODIFIED_BUSINESSES_REQUEST = "LOAD_MODIFIED_BUSINESSES_REQUEST",
  LOAD_MODIFIED_BUSINESSES_SUCCESS = "LOAD_MODIFIED_BUSINESSES_SUCCESS",
  LOAD_MODIFIED_BUSINESSES_FAILURE = "LOAD_MODIFIED_BUSINESSES_FAILURE",
  UPDATE_MODIFIED_BUSINESS = "UPDATE_MODIFIED_BUSINESS",
}
